#!/bin/sh

BROWSE=surf

WD=$(dirname $0)
TD=$(mktemp -td color.XXX)
trap "rm -rf $TD" 0 2 15

if [ ! -f $WD/mdcolor ]
then
	( cd $WD && make mdcolor )
fi

sha2() {
	if [ -x $(which sha256sum) ]
	then
		sha256sum $* | cut -d' ' -f1
	elif [ -x $(which sha256) ]
	then
		sha256 -q $*
	else
		echo "No sha256 found." 1>&2
	fi
}

PAGE=$TD/page.html
sha2 $* | xargs $WD/mdcolor | $WD/pagefmt > $PAGE && $BROWSE file://$PAGE
