#!/bin/sh

WD=$(dirname $0)
TD=$(mktemp -td color.XX)
trap "rm -rf $TD" 0 2 15

if [ ! -f $WD/mdcolor ]
then
	( cd $WD && make mdcolor )
fi

PAGE=$TD/page.html
sha256 -q $* | xargs $WD/mdcolor | $WD/pagefmt > $PAGE && surf $PAGE
