#!/usr/bin/env perl

use strict;
use warnings;

my $DIM = "2px";

my @colors = <STDIN>;
chomp @colors;

print <<EOF;
<!doctype html>
<style>
table{border-collapse:collapse}
td{width:$DIM;height:$DIM}
</style><table><tr>
EOF

print "</style><table><tr>";

foreach my $i (0 .. $#colors ) {
	print "<td style='background-color:#${colors[$i]}'></td>";
	if ($i % 4 == 3) {
		print "</tr><tr>";
	}
}
print "</tr></table>\n"
